---
- hosts: all

  pre_tasks:
    - name: Install dockutil
      community.general.homebrew:
        name: lotyp/formulae/dockutil

  tasks:
    - name: Browsers
      block:
        - name: Browsers - Install
          community.general.homebrew_cask:
            name:
              - brave-browser
              - vivaldi
              - google-chrome
              - firefox
        - name: Browsers - Dock
          dock-util:
            add:
              - hbc:google-chrome
              - hbc:vivaldi
              - hbc:brave-browser
            after: Launchpad
      ignore_errors: true

    - name: Utils
      block:
        - name: Utils - Install
          community.general.homebrew_cask:
            name:
              - path-finder
              - forklift
              - superduper
              - standard-notes

    - name: Office
      block:
        - name: Office - Install
          community.general.homebrew:
            name:
              - davmail
        - name: Office - Install
          community.general.homebrew_cask:
            name:
              - thunderbird
              - gimp
              - paintbrush
              - libreoffice

    - name: Others
      block:
        - name: Others - Install
          community.general.homebrew_cask:
            name:
              - discord
              - teamviewer
              - vlc
              - sonic-pi

    - name: Dev
      block:
        - name: Dev - Install
          community.general.homebrew_cask:
            name:
              - iterm2
              - textmate
              - visual-studio-code
              - sequel-ace
              - hex-fiend
              - vmware-fusion
              - apache-directory-studio
              - pycharm-ce
        - name: Dev - Install
          community.general.homebrew:
            name:
              - docker
