---
- hosts: all

  pre_tasks:
    - name: Install dockutil
      community.general.homebrew:
        name: lotyp/formulae/dockutil

  tasks:
    - name: Remove default apps from dock
      dock-util:
        remove:
          - /Applications/Safari.app
          - /System/Applications/Messages.app
          - /System/Applications/Mail.app
          - /System/Applications/Maps.app
          - /System/Applications/Photos.app
          - /System/Applications/FaceTime.app
          - /System/Applications/Calendar.app
          - /System/Applications/Contacts.app
          - /System/Applications/Reminders.app
          - /System/Applications/Notes.app
          - /System/Applications/TV.app
          - /System/Applications/Music.app
          - /System/Applications/Podcasts.app
          - /System/Applications/App Store.app
          - /System/Applications/System Preferences.app

    - name: Browsers
      block:
        - name: Browsers - Install
          community.general.homebrew_cask:
            name:
              - brave-browser
              - vivaldi
              - google-chrome
              - firefox
        - name: Browsers - Dock
          dock-util:
            add:
              - hbc:google-chrome
              - hbc:vivaldi
              - hbc:brave-browser
            after: Launchpad
      ignore_errors: true

    - name: Utils
      block:
        - name: Utils - Install
          community.general.homebrew_cask:
            name:
              - path-finder
              - forklift
              - superduper
              - standard-notes
        - name: Utils - Dock
          dock-util:
            add:
              - hbc:forklift
              - hbc:path-finder
            after: Launchpad

    - name: Office
      block:
        - name: Office - Install
          community.general.homebrew:
            name:
              - davmail
        - name: Office - Install
          community.general.homebrew_cask:
            name:
              - thunderbird
              - gimp
              - paintbrush
              - libreoffice
        - name: Office - Dock
          dock-util:
            add:
              - hbc:thunderbird
            after: hbc:forklift

    - name: Others
      block:
        - name: Others - Install
          community.general.homebrew_cask:
            name:
              - discord
              - teamviewer
              - vlc
              - sonic-pi
        - name: Others - Dock
          dock-util:
            add:
              - hbc:discord

    - name: Dev
      block:
        - name: Dev - Install
          community.general.homebrew_cask:
            name:
              - iterm2
              - textmate
              - visual-studio-code
              - sequel-ace
              - hex-fiend
              - vmware-fusion
              - apache-directory-studio
              - pycharm-ce
              - android-studio
              - flutter
        - name: Dev - Settings - flutter telemetry
          ansible.builtin.lineinfile:
            path: "{{ ansible_facts.user_dir }}/.dart-tool/dart-flutter-telemetry.config"
            create: true
            regexp: "^reporting="
            line: "reporting=0"
        - name: Dev - Install
          community.general.homebrew:
            name:
              - wget
              - docker
              - mariadb
              - sqlite
        - name: Dev - Dock
          dock-util:
            add:
              - hbc:vmware-fusion
              - hbc:sequel-ace
              - hbc:visual-studio-code
              - hbc:textmate
              - hbc:iterm2
            after: hbc:brave-browser
